# Generated by Django 4.1.7 on 2023-03-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='預設內文', max_length=500),
            preserve_default=False,
        ),
    ]
