# Generated by Django 4.1.7 on 2023-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0006_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="first.tag"),
        ),
    ]
