# Generated by Django 4.1.7 on 2023-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0007_post_image_alter_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userlogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="UserSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=255)),
                ("uname", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]

# 0008_userlogin.py
# # Generated by Django 4.1.7 on 2023-06-01 14:50

# from django.db import migrations, models


# class Migration(migrations.Migration):
#     dependencies = [
#         ("first", "0007_post_image_alter_post_tags"),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name="Userlogin",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("email", models.CharField(max_length=64, unique=True)),
#                 ("password", models.CharField(max_length=128)),
#             ],
#         ),
#     ]
