# Generated by Django 4.1.7 on 2023-06-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0008_userlogin_usersignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name="Userlogin",
        ),
        migrations.DeleteModel(
            name="UserSignup",
        ),
    ]
