# Generated by Django 4.1.7 on 2023-06-01 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0010_signup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="login",
        ),
    ]
