# Generated by Django 4.1.7 on 2023-06-01 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0013_rename_login_userlogin"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserLogin",
            new_name="login",
        ),
    ]
