# Generated by Django 4.1.7 on 2023-06-01 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0014_rename_userlogin_login"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="login",
            new_name="UserLogin",
        ),
    ]
