# Generated by Django 4.1.7 on 2023-11-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0016_alter_signup_email_alter_signup_fname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="posts/%Y"),
        ),
    ]
