# Generated by Django 4.1.7 on 2023-11-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0017_post_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
        migrations.AddField(
            model_name="post",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
