# Generated by Django 4.1.7 on 2023-11-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0018_remove_post_video_post_difficulty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(max_length=500)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="posts/%Y/%m/%d/"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="first.tag")),
            ],
        ),
    ]
