# Generated by Django 4.1.7 on 2023-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0022_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="gmail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="signup",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
