# Generated by Django 4.1.7 on 2023-12-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0024_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Signup",
        ),
        migrations.DeleteModel(
            name="UserLogin",
        ),
        migrations.AlterField(
            model_name="learner",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="learners/%Y/%m/%d/"
            ),
        ),
    ]
