# Generated by Django 4.1.7 on 2023-12-09 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0025_delete_signup_delete_userlogin_alter_learner_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
