# Generated by Django 4.1.7 on 2023-12-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0028_userprofile_username_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="images/anonymous.png", upload_to="avatars/"
            ),
        ),
    ]
