# Generated by Django 4.1.7 on 2023-12-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0034_learnercomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(default="未知發布時間"),
        ),
    ]

