# Generated by Django 4.1.7 on 2023-12-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0035_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
