# Generated by Django 4.1.7 on 2023-12-15 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0036_alter_comment_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="timer",
        ),
    ]
