# Generated by Django 4.1.7 on 2023-12-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0037_rename_created_at_comment_timer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="timer",
        ),
        migrations.AddField(
            model_name="comment",
            name="times",
            field=models.DateTimeField(auto_now_add=True, default=1998),
            preserve_default=False,
        ),
    ]
