# Generated by Django 4.1.7 on 2023-12-15 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0038_remove_comment_timer_comment_times"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="times",
        ),
    ]
